r266 nine one foxtrot delta

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -22,4 +22,28 @@ echo
 echo "  $(tput smul && tput setaf 6 || :)http://dev-api.stadia.st:57482/skus.json$(tput sgr0 || :)"
 echo
 
+(
+  sleep 1
+  declare output
+  output="$(
+    /Applications/"Google Chrome.app"/Contents/MacOS/"Google Chrome" \
+      --headless \
+      --user-data-dir="$HOME"/Library/"Application Support"/Google/Chrome/ \
+      'http://dev.stadia.run:57481/#dev-tools' 2>&1 \
+      | egrep --only-matching '<st-\w+>.*</st-\w+>' -A1 | cat || :)";
+  echo
+  if echo "$output" | grep -q '<st-event>load</st-event>'; then
+    if echo "$output" | grep -q '<st-error>'; then
+      echo "[headless ERROR] errors ocurred before page load:"
+      echo "$output" | grep '<st-error>' -A1
+      exit 1
+    else
+      echo "[headless INFO] no errors before page load"
+    fi
+  else
+    echo "[headless WARN] failed to load run headless test (was Chrome busy?)"
+  fi
+  echo
+) &
+
 wait
